export { default as TinogastaDetails } from "./Tinogasta/Tinogasta"
export { default as FiambalaDetails } from  "./Fiambala/Fiambala"
export { default as AntofagastaDeLaSierraDetails } from "./Antofagasta-De-La-Sierra/AntofagastaDeLaSierra"
export { default as CatamarcaDetails } from "./Catamarca/Catamarca"
export { default as Departamentos } from "./Departamentos/Departamentos"
export { default as HospedajeList } from "./Hospedaje/Hospedaje"
export { default as Logo } from "./Logo/Logo"
export { default as Loading } from "./Loading/Loading"