export { default as TinogastaDetails } from "./Tinogasta/TinogastaDetails"
export { default as FiambalaDetails } from  "./Fimbala/Fiambala"
export { default as AntofagastaDeLaSierraDetails } from "./Antofagasta-De-La-Sierra/AntofagastaDeLaSierraDetails"
export { default as CatamarcaDetails } from "./Catamarca/CatamarcaDetails"
export { default as Departamentos } from "./Departamentos/Departamentos"
export { default as HospedajeList } from "./Hospedaje/Hospedaje"
export { default as Logo } from "./Logo/Logo"
export { default as Loading } from "./Loading/Loading"